version: "3.3"
volumes:
  db_data:
  pgadmin_data:
  redis_data:
  db_data2:
services:
  placio-proxy:
    image: traefik:latest
    ports:
      - "80:80"
      - "8090:8080"
      - "443:443"
    env_file:
      - ./.envs/.stag

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/traefik.yml:/traefik.yml
      - /opt/traefik/acme.json:/acme.json
      - /opt/traefik/configurations:/configurations
    command:
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api
      # Enable the Dashboard and API in insecure mode for local development
      - --api.insecure=true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=default"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.palnight.com`)"
      # - 'traefik.http.routers.traefik-secure.middlewares=user-auth@file'
      - "traefik.http.routers.traefik-secure.service=api@internal"

  placio-db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/pg-data/pgdata
    env_file:
      - ./.envs/.stag
    networks:
      - default

  placio-backend:
    ports:
      - "7070:7070"
    env_file:
      - ./.envs/.stag
    volumes:
      - ./:/app
      - ./cmd/app:/app/cmd/app
      - ./config:/app/config
    build:
      context: .
      dockerfile: ./cmd/app/Dockerfile
    networks:
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=default
      - "traefik.http.routers.backend-secure.entrypoints=websecure"
      - "traefik.http.routers.backend-secure.rule=Host(`api.palnight.com`)"
      - "traefik.http.routers.backend-secure.service=backend"
      # - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      # - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      # - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      # - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      # - "traefik.http.routers.backend-secure.middlewares=cors"
      - traefik.http.services.backend.loadbalancer.server.port=7070

  docs:
    container_name: placio-docs
    build:
      context: .
      dockerfile: ./docs/Dockerfile
    restart: always
    ports:
      - "6060:6060"
    volumes:
      # - ./:/app
      - ./docs:/app/docs

    labels:
      - traefik.enable=true
      - traefik.docker.network=default
      - "traefik.http.routers.docs-secure.entrypoints=websecure"
      - "traefik.http.routers.docs-secure.rule=Host(`docs.palnight.com`)"
      - "traefik.http.routers.docs-secure.service=docs"
      - traefik.http.services.docs.loadbalancer.server.port=6060
      # add path prefix strip

  newrelic-infra:
    image: newrelic/infrastructure:latest
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - NRIA_LICENSE_KEY=eu01xx48a40b16fb787caed094a43278c919NRAL
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped

# volumes:
#   app-db-data2:
networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false
